# Generated by Django 5.2.8 on 2025-11-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_cocina', models.CharField(max_length=100)),
                ('tiempo_entrega_promedio', models.PositiveIntegerField(help_text='Tiempo en minutos')),
                ('calificacion', models.FloatField()),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('costo_envio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pedido_minimo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('imagen', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.DeleteModel(
            name='Pronostico',
        ),
    ]
